/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as RosterHandleRouteImport } from './routes/roster.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterHandleRoute = RosterHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => RosterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reels': typeof ReelsRoute
  '/rides': typeof RidesRoute
  '/roster': typeof RosterRouteWithChildren
  '/vault': typeof VaultRoute
  '/roster/$handle': typeof RosterHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reels': typeof ReelsRoute
  '/rides': typeof RidesRoute
  '/roster': typeof RosterRouteWithChildren
  '/vault': typeof VaultRoute
  '/roster/$handle': typeof RosterHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reels': typeof ReelsRoute
  '/rides': typeof RidesRoute
  '/roster': typeof RosterRouteWithChildren
  '/vault': typeof VaultRoute
  '/roster/$handle': typeof RosterHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/reels' | '/rides' | '/roster' | '/vault' | '/roster/$handle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reels' | '/rides' | '/roster' | '/vault' | '/roster/$handle'
  id:
    | '__root__'
    | '/'
    | '/reels'
    | '/rides'
    | '/roster'
    | '/vault'
    | '/roster/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReelsRoute: typeof ReelsRoute
  RidesRoute: typeof RidesRoute
  RosterRoute: typeof RosterRouteWithChildren
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$handle': {
      id: '/roster/$handle'
      path: '/$handle'
      fullPath: '/roster/$handle'
      preLoaderRoute: typeof RosterHandleRouteImport
      parentRoute: typeof RosterRoute
    }
  }
}

interface RosterRouteChildren {
  RosterHandleRoute: typeof RosterHandleRoute
}

const RosterRouteChildren: RosterRouteChildren = {
  RosterHandleRoute: RosterHandleRoute,
}

const RosterRouteWithChildren =
  RosterRoute._addFileChildren(RosterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReelsRoute: ReelsRoute,
  RidesRoute: RidesRoute,
  RosterRoute: RosterRouteWithChildren,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
